logging.level.org:
  springframework: DEBUG
  springdoc: DEBUG

server.port: 8080

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true