logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.springdoc: DEBUG
  file:
    name: logs/logger.log
#    path: logs

server.port: 8080

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true